const ALLOWED_DOMAINS = [
  'nitk.edu.in',
  'iiitd.ac.in',
  'vit.ac.in',
  'iitb.ac.in',
  'iitd.ac.in',
  'iitk.ac.in',
  'iitm.ac.in',
  'iitkgp.ac.in',
  'bits-pilani.ac.in',
  'nitt.edu',
  'iitr.ac.in',
  'iith.ac.in',
  'iiita.ac.in',
  'iitism.ac.in',
  'nits.ac.in',
  'nitw.ac.in',
  'mnnit.ac.in',
  'svnit.ac.in',
  'nitc.ac.in',
  'nitp.ac.in',
  'dtu.ac.in',
  'nsut.ac.in',
  'iiitb.ac.in',
  'iiith.ac.in',
  'lnmiit.ac.in',
  'da-iict.ac.in',
  'srmist.edu.in',
  'manipal.edu',
  'amity.edu',
  'lpu.in',
];

const BLOCKED_DOMAINS = [
  'gmail.com',
  'yahoo.com',
  'outlook.com',
  'hotmail.com',
  'protonmail.com',
  'icloud.com',
  'aol.com',
  'mail.com',
  'zoho.com',
];

module.exports = { ALLOWED_DOMAINS, BLOCKED_DOMAINS };
